apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s
spec:
  template:
    spec:
      # Prefer spreading replicas across nodes for availability.
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: hello-k8s
