apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hello-k8s
  labels:
    app.kubernetes.io/name: hello-k8s
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-k8s
