apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# Common labels applied across every resource.
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: hello-k8s
      app.kubernetes.io/managed-by: kustomize
